/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Delivery
import io.swagger.client.models.Order
import io.swagger.client.models.User

/**
 * 
 * @param id 
 * @param header 
 * @param country 
 * @param city 
 * @param street 
 * @param zipCode 
 * @param phoneNumber 
 * @param orders 
 * @param user 
 * @param sentDeliveries 
 * @param receivedDeliveries 
 * @param default 
 */
data class Address (

    val id: kotlin.String? = null,
    val header: kotlin.String? = null,
    val country: kotlin.String? = null,
    val city: kotlin.String? = null,
    val street: kotlin.String? = null,
    val zipCode: kotlin.String? = null,
    val phoneNumber: kotlin.String? = null,
    val orders: kotlin.Array<Order>? = null,
    val user: User? = null,
    val sentDeliveries: kotlin.Array<Delivery>? = null,
    val receivedDeliveries: kotlin.Array<Delivery>? = null,
    val default: kotlin.Boolean? = null
) {
}