/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CustomMoneyDTO
import io.swagger.client.models.ProductCategoryDTO
import io.swagger.client.models.ProductCreateDTO
import io.swagger.client.models.SizeDTO

/**
 * 
 * @param productGender 
 * @param clothingSize 
 * @param colour 
 */
data class ClothingCreateDTO (

    val productGender: ProductGender,
    val clothingSize: SizeDTO,
    val colour: Colour
) {
    /**
    * 
    * Values: MALE,FEMALE,UNISEX
    */
    enum class ProductGender(val value: kotlin.String){
        MALE("MALE"),
        FEMALE("FEMALE"),
        UNISEX("UNISEX");
    }
    /**
    * 
    * Values: YELLOW,GREEN,BLUE,RED,BLACK,WHITE,MULTICOLOUR
    */
    enum class Colour(val value: kotlin.String){
        YELLOW("YELLOW"),
        GREEN("GREEN"),
        BLUE("BLUE"),
        RED("RED"),
        BLACK("BLACK"),
        WHITE("WHITE"),
        MULTICOLOUR("MULTICOLOUR");
    }
}