/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * 
 * @param productGender 
 * @param clothingSize 
 * @param colour 
 */

class ClothingCreateDTO {
    constructor(
        title: kotlin.String? = null,
        description: kotlin.String? = null,
        productCost: CustomMoneyDTO,
        deliveryCost: CustomMoneyDTO,
        brand: kotlin.String? = null,
        condition: ProductCreateDTO.Condition? = null,
        productSize: ProductCreateDTO.ProductSize? = null,
        visibility: ProductCreateDTO.Visibility? = null,
        productCategory: ProductCategoryDTO? = null,
        productImages: kotlin.Array<kotlin.Array<kotlin.Byte>>? = null,
        type: kotlin.String,
        productGender: ProductGender,
        clothingSize: SizeDTO,
        colour: Colour
        )
    /**
    * 
    * Values: MALE,FEMALE,UNISEX
    */
    enum class ProductGender(val value: kotlin.String){
        MALE("MALE"),
        FEMALE("FEMALE"),
        UNISEX("UNISEX");
    }
    /**
    * 
    * Values: YELLOW,GREEN,BLUE,RED,BLACK,WHITE,MULTICOLOUR
    */
    enum class Colour(val value: kotlin.String){
        YELLOW("YELLOW"),
        GREEN("GREEN"),
        BLUE("BLUE"),
        RED("RED"),
        BLACK("BLACK"),
        WHITE("WHITE"),
        MULTICOLOUR("MULTICOLOUR");
    }
}