/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.MessageDTO
import io.swagger.client.models.ProductBasicDTO
import io.swagger.client.models.UserBasicDTO

/**
 * 
 * @param productBasicDTO 
 * @param otherUser 
 * @param lastMessage 
 * @param unreadMessages 
 * @param conversationId 
 */
data class ConversationDTO (

    val productBasicDTO: ProductBasicDTO? = null,
    val otherUser: UserBasicDTO,
    val lastMessage: MessageDTO,
    val unreadMessages: kotlin.Boolean,
    val conversationId: kotlin.String? = null
) {
}