/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param code 
 * @param numericCode 
 * @param decimalPlaces 
 * @param symbol 
 * @param numeric3Code 
 * @param countryCodes 
 * @param pseudoCurrency 
 */
data class CurrencyUnit (

    val code: kotlin.String? = null,
    val numericCode: kotlin.Int? = null,
    val decimalPlaces: kotlin.Int? = null,
    val symbol: kotlin.String? = null,
    val numeric3Code: kotlin.String? = null,
    val countryCodes: kotlin.Array<kotlin.String>? = null,
    val pseudoCurrency: kotlin.Boolean? = null
) {
}