/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param price 
 * @param currency 
 */
data class CustomMoneyDTO (

    val price: kotlin.Double? = null,
    val currency: Currency? = null
) {
    /**
    * 
    * Values: EUR,USD
    */
    enum class Currency(val value: kotlin.String){
        EUR("EUR"),
        USD("USD");
    }
}