/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AddressDTO
import io.swagger.client.models.CustomMoneyDTO
import io.swagger.client.models.OrderBasicDTO

/**
 * 
 * @param order 
 * @param sendTime 
 * @param deliveredTime 
 * @param deliveryCost 
 * @param shipper 
 * @param deliveryStatus 
 * @param senderAddress 
 * @param receiverAddress 
 * @param id 
 */
data class DeliveryDTO (

    val order: OrderBasicDTO? = null,
    val sendTime: java.time.LocalDateTime? = null,
    val deliveredTime: java.time.LocalDateTime? = null,
    val deliveryCost: CustomMoneyDTO? = null,
    val shipper: kotlin.String? = null,
    val deliveryStatus: DeliveryStatus? = null,
    val senderAddress: AddressDTO? = null,
    val receiverAddress: AddressDTO? = null,
    val id: kotlin.String? = null
) {
    /**
    * 
    * Values: SHIPPED,DELIVERED
    */
    enum class DeliveryStatus(val value: kotlin.String){
        SHIPPED("SHIPPED"),
        DELIVERED("DELIVERED");
    }
}