/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * 
 * @param colour 
 * @param homeSize 
 * @param homeMaterial 
 */
class HomeCreateDTO: ProductCreateDTO {
    constructor (
        title: kotlin.String? = null,
        description: kotlin.String? = null,
        productCost: CustomMoneyDTO,
        deliveryCost: CustomMoneyDTO,
        brand: kotlin.String? = null,
        condition: ProductCreateDTO.Condition? = null,
        productSize: ProductCreateDTO.ProductSize? = null,
        visibility: ProductCreateDTO.Visibility? = null,
        productCategory: ProductCategoryDTO? = null,
        productImages: kotlin.Array<kotlin.Array<kotlin.Byte>>? = null,
        type: kotlin.String,
        colour: HomeCreateDTO.Colour,
        homeSize: SizeDTO,
        homeMaterial: HomeCreateDTO.HomeMaterial) :
            super(
                title,
                description,
                productCost,
                deliveryCost,
                brand,
                condition,
                productSize,
                visibility,
                productCategory,
                productImages,
                type,
            )

    constructor(productCreateDTO: ProductCreateDTO,
                colour: HomeCreateDTO.Colour,
                homeSize: SizeDTO,
                homeMaterial: HomeCreateDTO.HomeMaterial): super(
        title = productCreateDTO.title,
        description = productCreateDTO.description,
        productCost = productCreateDTO.productCost,
        deliveryCost = productCreateDTO.deliveryCost,
        brand = productCreateDTO.brand,
        condition = productCreateDTO.condition,
        productSize = productCreateDTO.productSize,
        visibility = productCreateDTO.visibility,
        productCategory = productCreateDTO.productCategory,
        productImages = productCreateDTO.productImages,
        type = productCreateDTO.type,
    )
    /**
    * 
    * Values: YELLOW,GREEN,BLUE,RED,BLACK,WHITE,MULTICOLOUR
    */
    enum class Colour(val value: kotlin.String){
        YELLOW("YELLOW"),
        GREEN("GREEN"),
        BLUE("BLUE"),
        RED("RED"),
        BLACK("BLACK"),
        WHITE("WHITE"),
        MULTICOLOUR("MULTICOLOUR");
    }
    /**
    * 
    * Values: COTTON,LINEN,WOOL,ACRYLIC,CHIFFON,POLYAMIDENYLON,POLYESTER,SILK,CERAMIC,GLASS,STAINLESSSTEEL,PLASTIC,WOOD,STONE,PORCELAIN,SILVER,METAL,OTHER
    */
    enum class HomeMaterial(val value: kotlin.String){
        COTTON("Cotton"),
        LINEN("Linen"),
        WOOL("Wool"),
        ACRYLIC("Acrylic"),
        CHIFFON("Chiffon"),
        POLYAMIDENYLON("Polyamide_Nylon"),
        POLYESTER("Polyester"),
        SILK("Silk"),
        CERAMIC("Ceramic"),
        GLASS("Glass"),
        STAINLESSSTEEL("Stainless_Steel"),
        PLASTIC("Plastic"),
        WOOD("Wood"),
        STONE("Stone"),
        PORCELAIN("Porcelain"),
        SILVER("Silver"),
        METAL("Metal"),
        OTHER("Other");
    }
}