/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * 
 * @param colour 
 * @param homeSize 
 * @param homeMaterial 
 */
class HomeCreateDTO {
    constructor (
        title: kotlin.String? = null,
        description: kotlin.String? = null,
        productCost: CustomMoneyDTO,
        deliveryCost: CustomMoneyDTO,
        brand: kotlin.String? = null,
        condition: ProductCreateDTO.Condition? = null,
        productSize: ProductCreateDTO.ProductSize? = null,
        visibility: ProductCreateDTO.Visibility? = null,
        productCategory: ProductCategoryDTO? = null,
        productImages: kotlin.Array<kotlin.Array<kotlin.Byte>>? = null,
        type: kotlin.String,
        colour: HomeCreateDTO.Colour,
        homeSize: SizeDTO,
        homeMaterial: HomeCreateDTO.HomeMaterial)
    /**
    * 
    * Values: YELLOW,GREEN,BLUE,RED,BLACK,WHITE,MULTICOLOUR
    */
    enum class Colour(val value: kotlin.String){
        YELLOW("YELLOW"),
        GREEN("GREEN"),
        BLUE("BLUE"),
        RED("RED"),
        BLACK("BLACK"),
        WHITE("WHITE"),
        MULTICOLOUR("MULTICOLOUR");
    }
    /**
    * 
    * Values: COTTON,LINEN,WOOL,ACRYLIC,CHIFFON,POLYAMIDENYLON,POLYESTER,SILK,CERAMIC,GLASS,STAINLESSSTEEL,PLASTIC,WOOD,STONE,PORCELAIN,SILVER,METAL,OTHER
    */
    enum class HomeMaterial(val value: kotlin.String){
        Cotton("Cotton"),
        Linen("Linen"),
        Wool("Wool"),
        Acrylic("Acrylic"),
        Chiffon("Chiffon"),
        Polyamide_Nylon("Polyamide_Nylon"),
        Polyester("Polyester"),
        Silk("Silk"),
        Ceramic("Ceramic"),
        Glass("Glass"),
        Stainless_Steel("Stainless_Steel"),
        Plastic("Plastic"),
        Wood("Wood"),
        Stone("Stone"),
        Porcelain("Porcelain"),
        Silver("Silver"),
        Metal("Metal"),
        Other("Other");
    }
}