/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CustomMoneyDTO
import io.swagger.client.models.ProductCategoryDTO
import io.swagger.client.models.ProductCreateDTO
import io.swagger.client.models.SizeDTO

/**
 * 
 * @param colour 
 * @param homeSize 
 * @param homeMaterial 
 */
data class HomeCreateDTO (

    val colour: Colour,
    val homeSize: SizeDTO,
    val homeMaterial: HomeMaterial
) {
    /**
    * 
    * Values: YELLOW,GREEN,BLUE,RED,BLACK,WHITE,MULTICOLOUR
    */
    enum class Colour(val value: kotlin.String){
        YELLOW("YELLOW"),
        GREEN("GREEN"),
        BLUE("BLUE"),
        RED("RED"),
        BLACK("BLACK"),
        WHITE("WHITE"),
        MULTICOLOUR("MULTICOLOUR");
    }
    /**
    * 
    * Values: COTTON,LINEN,WOOL,ACRYLIC,CHIFFON,POLYAMIDENYLON,POLYESTER,SILK,CERAMIC,GLASS,STAINLESSSTEEL,PLASTIC,WOOD,STONE,PORCELAIN,SILVER,METAL,OTHER
    */
    enum class HomeMaterial(val value: kotlin.String){
        COTTON("Cotton"),
        LINEN("Linen"),
        WOOL("Wool"),
        ACRYLIC("Acrylic"),
        CHIFFON("Chiffon"),
        POLYAMIDENYLON("Polyamide_Nylon"),
        POLYESTER("Polyester"),
        SILK("Silk"),
        CERAMIC("Ceramic"),
        GLASS("Glass"),
        STAINLESSSTEEL("Stainless_Steel"),
        PLASTIC("Plastic"),
        WOOD("Wood"),
        STONE("Stone"),
        PORCELAIN("Porcelain"),
        SILVER("Silver"),
        METAL("Metal"),
        OTHER("Other");
    }
}