/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ProductBasicDTO
import io.swagger.client.models.UserBasicDTO

/**
 * 
 * @param conversationId 
 * @param text 
 * @param product 
 * @param receivedUser 
 */
data class MessageCreateDTO (

    val conversationId: kotlin.String? = null,
    val text: kotlin.String,
    val product: ProductBasicDTO? = null,
    val receivedUser: UserBasicDTO
) {
}