/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AddressDTO
import io.swagger.client.models.OfferBasicDTO
import io.swagger.client.models.ProductBasicDTO

/**
 * 
 * @param product 
 * @param offer 
 * @param deliveryAddress 
 */
data class OrderCreateDTO (

    val product: ProductBasicDTO,
    val offer: OfferBasicDTO? = null,
    val deliveryAddress: AddressDTO
) {
}