/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Address
import io.swagger.client.models.Delivery
import io.swagger.client.models.Offer
import io.swagger.client.models.Product
import io.swagger.client.models.Transaction
import io.swagger.client.models.User

/**
 * 
 * @param id 
 * @param orderDate 
 * @param orderUpdateDate 
 * @param state 
 * @param product 
 * @param user 
 * @param delivery 
 * @param deliveryAddress 
 * @param offer 
 * @param transaction 
 */
data class Order (

    val id: kotlin.String? = null,
    val orderDate: java.time.LocalDateTime? = null,
    val orderUpdateDate: java.time.LocalDateTime? = null,
    val state: State? = null,
    val product: Product? = null,
    val user: User? = null,
    val delivery: Delivery? = null,
    val deliveryAddress: Address? = null,
    val offer: Offer? = null,
    val transaction: Transaction? = null
) {
    /**
    * 
    * Values: CANCELED,PENDING,PURCHASED,SHIPPED,DELIVERED,COMPLETED,REVIEWED
    */
    enum class State(val value: kotlin.String){
        CANCELED("CANCELED"),
        PENDING("PENDING"),
        PURCHASED("PURCHASED"),
        SHIPPED("SHIPPED"),
        DELIVERED("DELIVERED"),
        COMPLETED("COMPLETED"),
        REVIEWED("REVIEWED");
    }
}