/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.SortObject

/**
 * 
 * @param offset 
 * @param sort 
 * @param pageNumber 
 * @param pageSize 
 * @param unpaged 
 * @param paged 
 */
data class PageableObject (

    val offset: kotlin.Long? = null,
    val sort: SortObject? = null,
    val pageNumber: kotlin.Int? = null,
    val pageSize: kotlin.Int? = null,
    val unpaged: kotlin.Boolean? = null,
    val paged: kotlin.Boolean? = null
) {
}