/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CustomMoneyDTO
import io.swagger.client.models.ProductCategoryDTO

/**
 * 
 * @param title 
 * @param description 
 * @param productCost 
 * @param deliveryCost 
 * @param brand 
 * @param condition 
 * @param productSize 
 * @param visibility 
 * @param productCategory 
 * @param productImages 
 * @param type 
 */
open class ProductCreateDTO (

    val title: kotlin.String? = null,
    val description: kotlin.String? = null,
    val productCost: CustomMoneyDTO,
    val deliveryCost: CustomMoneyDTO,
    val brand: kotlin.String? = null,
    val condition: Condition? = null,
    val productSize: ProductSize? = null,
    val visibility: Visibility? = null,
    val productCategory: ProductCategoryDTO? = null,
    val productImages: kotlin.Array<kotlin.Array<kotlin.Byte>>? = null,
    val type: kotlin.String
) {
    /**
    * 
    * Values: NEWWITHTAG,NEWWITHOUTTAG,VERYGOOD,GOOD,ACCEPTABLE
    */
    enum class Condition(val value: kotlin.String){
        NEW_WITH_TAG("NEW_WITH_TAG"),
        NEW_WITHOUT_TAG("NEW_WITHOUT_TAG"),
        VERY_GOOD("VERY_GOOD"),
        GOOD("GOOD"),
        ACCEPTABLE("ACCEPTABLE");
    }
    /**
    * 
    * Values: BIG,MEDIUM,SMALL
    */
    enum class ProductSize(val value: kotlin.String){
        BIG("BIG"),
        MEDIUM("MEDIUM"),
        SMALL("SMALL");
    }
    /**
    * 
    * Values: PUBLIC,PRIVATE
    */
    enum class Visibility(val value: kotlin.String){
        PUBLIC("PUBLIC"),
        PRIVATE("PRIVATE");
    }
}