/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CustomMoneyDTO
import io.swagger.client.models.ProductCategoryDTO
import io.swagger.client.models.ProductImageDTO
import io.swagger.client.models.UserBasicDTO

/**
 * 
 * @param id 
 * @param title 
 * @param description 
 * @param uploadDate 
 * @param productCost 
 * @param deliveryCost 
 * @param brand 
 * @param condition 
 * @param likesNumber 
 * @param seller 
 * @param productImages 
 * @param productCategory 
 */
data class ProductBasicDTO (

    val id: kotlin.String,
    val title: kotlin.String,
    val description: kotlin.String? = null,
    val uploadDate: java.time.LocalDateTime? = null,
    val productCost: CustomMoneyDTO,
    val deliveryCost: CustomMoneyDTO,
    val brand: kotlin.String? = null,
    val condition: Condition? = null,
    val likesNumber: kotlin.Int? = null,
    val seller: UserBasicDTO? = null,
    val productImages: kotlin.Array<ProductImageDTO>? = null,
    val productCategory: ProductCategoryDTO? = null
) {
    /**
    * 
    * Values: NEWWITHTAG,NEWWITHOUTTAG,VERYGOOD,GOOD,ACCEPTABLE
    */
    enum class Condition(val value: kotlin.String){
        NEW_WITH_TAG("New with tag"),
        NEW_WITHOUT_TAG("New without tag"),
        VERY_GOOD("Very good"),
        GOOD("Good"),
        ACCEPTABLE("Acceptable");
    }
}