/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * 
 * @param title 
 * @param description 
 * @param productCost 
 * @param deliveryCost 
 * @param brand 
 * @param condition 
 * @param productSize 
 * @param visibility 
 * @param productCategory
 * @param type 
 */
open class ProductCreateDTO(

    val title: String?,
    val description: String? = null,
    val productCost: CustomMoneyDTO,
    val deliveryCost: CustomMoneyDTO,
    val brand: String? = null,
    val condition: Condition?,
    val productSize: ProductSize?,
    val visibility: Visibility?,
    val productCategory: ProductCategoryDTO?,
    val productImages: Array<Array<Byte>>?,
    val type: String?,
    var colour: HomeCreateDTO.Colour?,
    var homeSize: SizeDTO?,
    var homeMaterial: HomeCreateDTO.HomeMaterial?,
    var productGender: ClothingCreateDTO.ProductGender?,
    var clothingSize: SizeDTO?,
    var entertainmentLanguage: EntertainmentCreateDTO.EntertainmentLanguage?
) {

    /*constructor(
        title: String?,
        description: String?,
        productCost: CustomMoneyDTO,
        deliveryCost: CustomMoneyDTO,
        brand: String?,
        condition: Condition?,
        productSize: ProductSize?,
        visibility: Visibility?,
        productCategory: ProductCategoryDTO?,
        productImages: Array<Array<Byte>>?,
        type: String?,
        colour: HomeCreateDTO.Colour,
        homeSize: SizeDTO,
        homeMaterial: HomeCreateDTO.HomeMaterial
    ) : this(
        title,
        description,
        productCost,
        deliveryCost,
        brand,
        condition,
        productSize,
        visibility,
        productCategory,
        productImages,
        type,
        colour,
        homeSize,
        homeMaterial
    )*/

    /**
    * 
    * Values: NEWWITHTAG,NEWWITHOUTTAG,VERYGOOD,GOOD,ACCEPTABLE
    */
    enum class Condition(val value: kotlin.String){
        NEW_WITH_TAG("NEW_WITH_TAG"),
        NEW_WITHOUT_TAG("NEW_WITHOUT_TAG"),
        VERY_GOOD("VERY_GOOD"),
        GOOD("GOOD"),
        ACCEPTABLE("ACCEPTABLE");
    }
    /**
    * 
    * Values: BIG,MEDIUM,SMALL
    */
    enum class ProductSize(val value: kotlin.String){
        BIG("BIG"),
        MEDIUM("MEDIUM"),
        SMALL("SMALL");
    }
    /**
    * 
    * Values: PUBLIC,PRIVATE
    */
    enum class Visibility(val value: kotlin.String){
        PUBLIC("PUBLIC"),
        PRIVATE("PRIVATE");
    }
}