/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CustomMoneyDTO
import io.swagger.client.models.ProductCategoryDTO
import io.swagger.client.models.ProductImageDTO
import io.swagger.client.models.UserBasicDTO

/**
 * 
 * @param id 
 * @param title 
 * @param description 
 * @param uploadDate 
 * @param productCost 
 * @param deliveryCost 
 * @param brand 
 * @param condition 
 * @param likesNumber 
 * @param seller 
 * @param productImages 
 * @param productCategory 
 */
data class ProductBasicDTO (

    val id: kotlin.String? = null,
    val title: kotlin.String? = null,
    val description: kotlin.String? = null,
    val uploadDate: java.time.LocalDateTime? = null,
    val productCost: CustomMoneyDTO,
    val deliveryCost: CustomMoneyDTO,
    val brand: kotlin.String? = null,
    val condition: Condition? = null,
    val likesNumber: kotlin.Int? = null,
    val seller: UserBasicDTO? = null,
    val productImages: ProductImageDTO? = null,
    val productCategory: ProductCategoryDTO? = null
) {
    /**
    * 
    * Values: NEWWITHTAG,NEWWITHOUTTAG,VERYGOOD,GOOD,ACCEPTABLE
    */
    enum class Condition(val value: kotlin.String){
        NEWWITHTAG("NEW_WITH_TAG"),
        NEWWITHOUTTAG("NEW_WITHOUT_TAG"),
        VERYGOOD("VERY_GOOD"),
        GOOD("GOOD"),
        ACCEPTABLE("ACCEPTABLE");
    }
}