/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param primaryCat 
 * @param secondaryCat 
 * @param tertiaryCat 
 */
data class ProductCategoryDTO (

    val id: kotlin.String? = null,
    val primaryCat: kotlin.String,
    val secondaryCat: kotlin.String,
    val tertiaryCat: kotlin.String
) {
}