/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.UserBasicDTO
import java.time.LocalDateTime

/**
 * 
 * @param id 
 * @param title 
 * @param description 
 * @param uploadDate 
 * @param productCost 
 * @param deliveryCost 
 * @param brand 
 * @param condition 
 * @param likesNumber 
 * @param seller 
 * @param productImages 
 * @param productCategory 
 */
data class ProductBasicDTO(

    val id: String? = null,
    val title: String? = null,
    val description: String? = null,
    val uploadDate: LocalDateTime? = null,
    val productCost: CustomMoneyDTO,
    val deliveryCost: CustomMoneyDTO,
    val brand: String? = null,
    val condition: Condition? = null,
    val likesNumber: Int? = null,
    val seller: UserBasicDTO? = null,
    val productImages: List<ProductImageDTO>? = null,
    val productCategory: ProductCategoryDTO? = null
) {
    /**
    * 
    * Values: NEWWITHTAG,NEWWITHOUTTAG,VERYGOOD,GOOD,ACCEPTABLE
    */
    enum class Condition(val value: kotlin.String){
        NEW_WITH_TAG("NEW_WITH_TAG"),
        NEW_WITHOUT_TAG("NEW_WITHOUT_TAG"),
        VERY_GOOD("VERY_GOOD"),
        GOOD("GOOD"),
        ACCEPTABLE("ACCEPTABLE");
    }
}