/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.UserBasicDTO
import java.time.LocalDateTime

/**
 * 
 * @param id 
 * @param reporterUser 
 * @param description 
 * @param reportedUser 
 * @param reportedProduct 
 * @param date 
 * @param lastUpdate 
 * @param status 
 * @param adminFollowedReport 
 */
data class ReportDTO(

    val id: String? = null,
    val reporterUser: UserBasicDTO? = null,
    val description: String? = null,
    val reportedUser: UserBasicDTO? = null,
    val reportedProduct: ProductDTO? = null,
    val date: LocalDateTime? = null,
    val lastUpdate: LocalDateTime? = null,
    val status: Status? = null,
    val adminFollowedReport: UserBasicDTO? = null
) {
    /**
    * 
    * Values: PENDING,CLOSED
    */
    enum class Status(val value: kotlin.String){
        PENDING("PENDING"),
        CLOSED("CLOSED");
    }
}