/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.User

/**
 * 
 * @param id 
 * @param date 
 * @param title 
 * @param description 
 * @param vote 
 * @param reviewer 
 * @param reviewed 
 */
data class Review (

    val id: kotlin.String? = null,
    val date: java.time.LocalDateTime? = null,
    val title: kotlin.String? = null,
    val description: kotlin.String? = null,
    val vote: kotlin.Int? = null,
    val reviewer: User? = null,
    val reviewed: User? = null
) {
}