/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.OrderBasicDTO
import io.swagger.client.models.PaymentMethodBasicDTO

/**
 * 
 * @param paymentMethod 
 * @param order 
 */
data class TransactionCreateDTO (

    val paymentMethod: PaymentMethodBasicDTO,
    val order: OrderBasicDTO
) {
}