/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Address
import io.swagger.client.models.Following
import io.swagger.client.models.GrantedAuthority
import io.swagger.client.models.Message
import io.swagger.client.models.Notification
import io.swagger.client.models.Offer
import io.swagger.client.models.Order
import io.swagger.client.models.PaymentMethod
import io.swagger.client.models.Product
import io.swagger.client.models.Report
import io.swagger.client.models.Review
import io.swagger.client.models.UserImage

/**
 * 
 * @param id 
 * @param username 
 * @param password 
 * @param email 
 * @param bio 
 * @param photoProfile 
 * @param provider 
 * @param addresses 
 * @param role 
 * @param emailVerified 
 * @param paymentMethods 
 * @param offersMade 
 * @param sellingProducts 
 * @param followers 
 * @param following 
 * @param followersNumber 
 * @param followingNumber 
 * @param reviewsTotalSum 
 * @param reviewsNumber 
 * @param likedProducts 
 * @param sentMessages 
 * @param receivedMessages 
 * @param orders 
 * @param receivedReviews 
 * @param sentReviews 
 * @param status 
 * @param reports 
 * @param reported 
 * @param adminFollowedMyReport 
 * @param notifications 
 * @param enabled 
 * @param administrator 
 * @param authorities 
 * @param credentialsNonExpired 
 * @param accountNonExpired 
 * @param accountNonLocked 
 */
data class User (

    val id: kotlin.String? = null,
    val username: kotlin.String? = null,
    val password: kotlin.String? = null,
    val email: kotlin.String? = null,
    val bio: kotlin.String? = null,
    val photoProfile: UserImage? = null,
    val provider: Provider? = null,
    val addresses: kotlin.Array<Address>? = null,
    val role: Role? = null,
    val emailVerified: kotlin.Boolean? = null,
    val paymentMethods: kotlin.Array<PaymentMethod>? = null,
    val offersMade: kotlin.Array<Offer>? = null,
    val sellingProducts: kotlin.Array<Product>? = null,
    val followers: kotlin.Array<Following>? = null,
    val following: kotlin.Array<Following>? = null,
    val followersNumber: kotlin.Int? = null,
    val followingNumber: kotlin.Int? = null,
    val reviewsTotalSum: kotlin.Int? = null,
    val reviewsNumber: kotlin.Int? = null,
    val likedProducts: kotlin.Array<Product>? = null,
    val sentMessages: kotlin.Array<Message>? = null,
    val receivedMessages: kotlin.Array<Message>? = null,
    val orders: kotlin.Array<Order>? = null,
    val receivedReviews: kotlin.Array<Review>? = null,
    val sentReviews: kotlin.Array<Review>? = null,
    val status: Status? = null,
    val reports: kotlin.Array<Report>? = null,
    val reported: kotlin.Array<Report>? = null,
    val adminFollowedMyReport: kotlin.Array<Report>? = null,
    val notifications: kotlin.Array<Notification>? = null,
    val enabled: kotlin.Boolean? = null,
    val administrator: kotlin.Boolean? = null,
    val authorities: kotlin.Array<GrantedAuthority>? = null,
    val credentialsNonExpired: kotlin.Boolean? = null,
    val accountNonExpired: kotlin.Boolean? = null,
    val accountNonLocked: kotlin.Boolean? = null
) {
    /**
    * 
    * Values: LOCAL,GOOGLE
    */
    enum class Provider(val value: kotlin.String){
        LOCAL("LOCAL"),
        GOOGLE("GOOGLE");
    }
    /**
    * 
    * Values: ADMIN,USER,SUPERADMIN
    */
    enum class Role(val value: kotlin.String){
        ADMIN("ADMIN"),
        USER("USER"),
        SUPERADMIN("SUPER_ADMIN");
    }
    /**
    * 
    * Values: ACTIVE,BANNED,HIDDEN,HOLIDAY,CANCELLED
    */
    enum class Status(val value: kotlin.String){
        ACTIVE("ACTIVE"),
        BANNED("BANNED"),
        HIDDEN("HIDDEN"),
        HOLIDAY("HOLIDAY"),
        CANCELLED("CANCELLED");
    }
}