/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.UserImageDTO

/**
 * 
 * @param id 
 * @param username 
 * @param bio 
 * @param photoProfile 
 * @param reviewsTotalSum 
 * @param reviewsNumber 
 * @param followersNumber 
 * @param followingNumber 
 */
data class UserBasicDTO (

    val id: kotlin.String? = null,
    val username: kotlin.String,
    val bio: kotlin.String? = null,
    val photoProfile: UserImageDTO? = null,
    val reviewsTotalSum: kotlin.Int? = null,
    val reviewsNumber: kotlin.Int? = null,
    val followersNumber: kotlin.Int? = null,
    val followingNumber: kotlin.Int? = null
) {
}