/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import com.enterprise.android_app.controller.BasePath
import io.swagger.client.models.FollowingFollowersDTO
import io.swagger.client.models.PageFollowingFollowersDTO

import io.swagger.client.infrastructure.*

class FollowingControllerApi(basePath: kotlin.String = com.enterprise.android_app.controller.BasePath.BASE_PATH) : ApiClient(basePath) {

    /**
     * 
     * 
     * @param userId  
     * @return FollowingFollowersDTO
     */
    @Suppress("UNCHECKED_CAST")
    fun follow(userId: kotlin.String): FollowingFollowersDTO {
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/api/v1/follow/{userId}".replace("{" + "userId" + "}", "$userId")
        )
        val response = request<FollowingFollowersDTO>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as FollowingFollowersDTO
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param userId  
     * @param page  (optional, default to 0)
     * @param sizePage  (optional, default to 10)
     * @return PageFollowingFollowersDTO
     */
    @Suppress("UNCHECKED_CAST")
    fun getFollowersOfUser(userId: kotlin.String, page: kotlin.Int? = null, sizePage: kotlin.Int? = null): PageFollowingFollowersDTO {
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>().apply {
            if (page != null) {
                put("page", listOf(page.toString()))
            }
            if (sizePage != null) {
                put("sizePage", listOf(sizePage.toString()))
            }
        }
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v1/followers/{userId}".replace("{" + "userId" + "}", "$userId"), query = localVariableQuery
        )
        val response = request<PageFollowingFollowersDTO>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as PageFollowingFollowersDTO
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param userId  
     * @param page  (optional, default to 0)
     * @param sizePage  (optional, default to 10)
     * @return PageFollowingFollowersDTO
     */
    @Suppress("UNCHECKED_CAST")
    fun getFollowingByUser(userId: kotlin.String, page: kotlin.Int? = null, sizePage: kotlin.Int? = null): PageFollowingFollowersDTO {
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>().apply {
            if (page != null) {
                put("page", listOf(page.toString()))
            }
            if (sizePage != null) {
                put("sizePage", listOf(sizePage.toString()))
            }
        }
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v1/following/{userId}".replace("{" + "userId" + "}", "$userId"), query = localVariableQuery
        )
        val response = request<PageFollowingFollowersDTO>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as PageFollowingFollowersDTO
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param userId  
     * @return kotlin.Boolean
     */
    @Suppress("UNCHECKED_CAST")
    fun imFollowingThisUser(userId: kotlin.String): kotlin.Boolean {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v1/me/following/{userId}".replace("{" + "userId" + "}", "$userId")
        )
        val response = request<kotlin.Boolean>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Boolean
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param userId  
     * @return void
     */
    fun unfollow(userId: kotlin.String): Unit {
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/api/v1/follow/{userId}".replace("{" + "userId" + "}", "$userId")
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
